## When there is a problem with routing, please enable this file!

## The current "attribute" function is not perfect yet.
## Every time the version is updated, routing problems will occur.
#controllers:
#    resource: ../../src/Controller/
#    type: attribute
#    prefix:
#        ja: '/ja-jp'
#        en: '/en-us'
#        zh: '/zh-cn'
